version: '3.9'
services:
  backend:
    image: node:18.16-bullseye
    command: yarn start
    working_dir: /opt/app
    volumes:
      - '.:/opt/app'
    ports:
      - '3333:3333'
  database:
    image: mongo:6.0.5-jammy
    ports:
      - '27017:27017'
